---
title: "2024_11_21_SDMCS_bowen"
author: "Jay Matsushiba"
date: "2024-11-21"
output: html_document
---

```{r setup}
devtools::install_github("Palen-Lab/sdmcsr", upgrade = "never")
devtools::install_github("Palen-Lab/rinat")

library(sdmcsr)
library(rinat)

library(tidyverse)
library(terra)
library(sf)
```

```{r}
if(!dir.exists("/media/jay/2TB_Drive/2024_11_27_SDM/Fish_mask")) {
  dir.create("/media/jay/2TB_Drive/2024_11_27_SDM")
  dir.create("/media/jay/2TB_Drive/2024_11_27_SDM/Fish_mask")
  dir.create("/media/jay/2TB_Drive/2024_11_27_SDM/MammalSmall_mask")
  dir.create("/media/jay/2TB_Drive/2024_11_27_SDM/Bird_mask")
  dir.create("/media/jay/2TB_Drive/2024_11_27_SDM/Amphibian_mask")
  dir.create("/media/jay/2TB_Drive/2024_11_27_SDM/Reptile_mask")
}

# Nov 28 2024
# rename fish SDMs
fish_sdm_filepaths <- list.files(
  path = "/media/jay/2TB_Drive/Zonation collaboration data (2024)/SPECIES/Fish_mask/",
  pattern = "*.tif$"
)

readxl::excel_sheets("/media/jay/2TB_Drive/Zonation collaboration data (2024)/SPECIES/Species_Appendix_v2.xlsx")
# [1] "species"    "fish"       "introduced" "missing"   

fish_sdm_acronyms <- readxl::read_xlsx(
  path = "/media/jay/2TB_Drive/Zonation collaboration data (2024)/SPECIES/Species_Appendix_v2.xlsx",
  sheet = "fish"
)

for(i in 1:nrow(fish_sdm_acronyms)) {
  fish_sdm_acronym <- fish_sdm_acronyms[i, "shortform (SDM folder)"][1] %>%
    unlist() %>%
    unname()
  fish_sdm_species <- fish_sdm_acronyms[i, "Species name"][1] %>%
    unlist() %>%
    unname() %>%
    gsub(" ", "\\.", .)
  fish_sdm_common <- fish_sdm_acronyms[i, "Common name"][1] %>%
    unlist() %>%
    unname()
  
  matchthis <- paste0("^", fish_sdm_acronym, "_")
  
  fish_sdm_filepath  <- fish_sdm_filepaths[grepl(matchthis, fish_sdm_filepaths)] %>%
    paste0("/media/jay/2TB_Drive/Zonation collaboration data (2024)/SPECIES/Fish_mask/", .)
  fish_sdm_filepath_base <- fish_sdm_filepaths[grepl(matchthis, fish_sdm_filepaths)]
  
  
  # fish_sdm_acronym %>% print()
  # fish_sdm_species %>% print()
  # fish_sdm_filepath %>%
  #   print()
  
  fish_sdm_filepath_new <- fish_sdm_filepath_base %>% 
    gsub(pattern = paste0("^", fish_sdm_acronym),
         replacement = fish_sdm_species,
         .) %>%
    paste0("/media/jay/2TB_Drive/2024_11_27_SDM/Fish_mask/", .)
  
  fish_sdm_acronym %>% message("Acronym: ", .)
  fish_sdm_species %>% message("Species: ", .)
  fish_sdm_common %>% message("Common name: ", .)
  fish_sdm_filepath %>% message("Original file: ", .)
  fish_sdm_filepath_new %>% message("New file: ", .)
  message("-------------------------------------------------------------------")
  
  fish_sdm <- terra::rast(fish_sdm_filepath) %>%
    terra::writeRaster(fish_sdm_filepath_new, 
                       overwrite=T)
}

```

```{r rescale_sdm}
SDMs_og_path <- list.files("/media/jay/2TB_Drive/2024_11_27_SDM/", 
                           pattern = "*.tif$",
                           recursive = TRUE,
                           full.names = TRUE) 

for(i in 1:length(SDMs_og_path)) {
  SDM_rast <- terra::rast(SDMs_og_path[i])
  SDM_rast_minmax <- terra::minmax(SDM_rast)
  if(SDM_rast_minmax[2] > 1) {
    SDM_rast <- SDM_rast / 1000
  }
  filename <- SDMs_og_path[i] %>%
    gsub("2024_11_27_SDM", 
         "2024_11_27_SDM_rescaled",
         .)
  
  if(!dir.exists("/media/jay/2TB_Drive/2024_11_27_SDM_rescaled")) {
    dir.create("/media/jay/2TB_Drive/2024_11_27_SDM_rescaled")
    dir.create("/media/jay/2TB_Drive/2024_11_27_SDM_rescaled/Fish_mask")
    dir.create("/media/jay/2TB_Drive/2024_11_27_SDM_rescaled/MammalSmall_mask")
    dir.create("/media/jay/2TB_Drive/2024_11_27_SDM_rescaled/Bird_mask")
    dir.create("/media/jay/2TB_Drive/2024_11_27_SDM_rescaled/Amphibian_mask")
    dir.create("/media/jay/2TB_Drive/2024_11_27_SDM_rescaled/Reptile_mask")
  }

  message(filename, " saved.")
  terra::writeRaster(SDM_rast, filename)
}
```


Crop SDMs
```{r}
SDMs_rescaled_path <- list.files("/media/jay/2TB_Drive/2024_11_27_SDM_rescaled/", 
                           pattern = "*.tif$",
                           recursive = TRUE,
                           full.names = TRUE) 
bowen_boundary <- terra::vect("RawData/bowen_boundary/Bowen_boundary.shp")

for(i in 1:length(SDMs_rescaled_path)) {
  SDM_rast <- terra::rast(SDMs_rescaled_path[i])
  filename <- SDMs_rescaled_path[i] %>%
    gsub("2024_11_27_SDM_rescaled", 
         "2024_11_28_SDM_Bowen_Island",
         .)
  
  if(!dir.exists("/media/jay/2TB_Drive/2024_11_28_SDM_Bowen_Island/")) {
    dir.create("/media/jay/2TB_Drive/2024_11_28_SDM_Bowen_Island/")
    dir.create("/media/jay/2TB_Drive/2024_11_28_SDM_Bowen_Island/Fish_mask")
    dir.create("/media/jay/2TB_Drive/2024_11_28_SDM_Bowen_Island/MammalSmall_mask")
    dir.create("/media/jay/2TB_Drive/2024_11_28_SDM_Bowen_Island/Bird_mask")
    dir.create("/media/jay/2TB_Drive/2024_11_28_SDM_Bowen_Island/Amphibian_mask")
    dir.create("/media/jay/2TB_Drive/2024_11_28_SDM_Bowen_Island/Reptile_mask")
  }

  message(filename, " saved.")
  SDM_rast_crop <- terra::crop(SDM_rast, bowen_boundary)
  terra::writeRaster(SDM_rast_crop, filename)
}

```


```{r}
# Bowen Island Boundary
area <- sf::st_read("RawData/bowen_boundary/Bowen_boundary.shp")

# Available SDMs
SDM_dir <- "/media/jay/2TB_Drive/2024_11_28_SDM_Bowen_Island/"
SDM_filepaths <- list.files(SDM_dir, recursive = T) 
SDM_filepaths <- SDM_filepaths[grepl("_NAs_", SDM_filepaths)]

# Create species list from available SDMs
species_list <- SDM_filepaths %>%
  basename() %>%
  stringr::str_extract("^\\S+\\.[a-zA-Z]+_") %>%
  stringr::str_remove("_") %>%
  stringr::str_replace("\\.", " ")

type_list <- SDM_filepaths %>%
  dirname() %>%
  str_remove("_mask")

bowen_SDM_iNat <- SDM_iNat_congruence(SDM_dir = SDM_dir, 
                                      species_list = species_list,
                                      area = area,
                                      mask_NA = T)

bowen_SDM_iNat$taxon_group <- type_list

write.csv(bowen_SDM_iNat, "ProcessedData/2024_11_29_SDM_CS_all_species")

```

# GENERATE FOCAL SPECIES LIST
```{r}
# iNat observations from rinat fork for Palen-Lab
# SDM maximum values anywhere on Bowen Island, generated from Zonation Collaboration 2014 SDMs 
bowen_SDM_iNat <- read.csv("ProcessedData/2024_11_29_SDM_CS_all_species")

# Mammal presences from Pottinger Gaherty Environmental Consultants, Ltd.(January 2005) 
bowen_mammals <- readxl::read_xlsx("/media/jay/2TB_Drive/2024_Bowen_Biodiversity_Project/Appendix 2 - Expected Occurrence of Wildlife Species In The Cape Roger Curtis Area.xlsx", sheet = "mammals") %>%
  filter(`Documented on Bowen` == "y" | `Documented on Bowen` == "?" | `Documented on Bowen` == "One or more spp" )

# number of eBird observations by bird species on Bowen Island
bowen_birds <- read.csv("RawData/final_bird.csv") %>%
  select(c("scientific_name", "n_ebird"))


bowen_SDM_iNat_ebird <- merge(bowen_SDM_iNat, 
                              bowen_birds, 
                              by.x = "species", 
                              by.y = "scientific_name",
                              all.x = TRUE) %>%
  rename(n_obs_inat = inat_n_obs,
         n_obs_ebird = n_ebird) %>%
  select(
    species,
    sdm_max_value,
    taxon_group,
    n_obs_inat,
    n_obs_ebird
  )
```

# Create species richness maps by different thresholds
```{r}
include_threshold <- 0.5 # threshold for including species as present 
bowen_SDM_obs_focal_df <- bowen_SDM_iNat_ebird %>%
  mutate(include = case_when(
    (n_obs_inat > 0 | n_obs_ebird > 0 ) & sdm_max_value > include_threshold ~ "y",
    species %in% bowen_mammals$`Scientific name` ~ "y"
    )
  )

# Create list of species names to include
bowen_focal_list <- bowen_SDM_obs_focal_df %>%
  filter(include == "y") %>%
  select(species) 
bowen_focal_list <- bowen_focal_list$species %>%
  unlist() %>%
  unname() 

# Get Bowen Island SDMs filepaths for the focal species
# Available SDMs
SDM_dir <- "/media/jay/2TB_Drive/2024_Bowen_Biodiversity_Project/2024_11_28_SDM_Bowen_Island/"
SDM_filepaths <- list.files(SDM_dir, recursive = T, full.names = T) 
SDM_filepaths <- SDM_filepaths[grepl("_NAs_", SDM_filepaths)]
SDM_species <- SDM_filepaths %>%
  basename() %>%
  stringr::str_extract("^\\S+\\.[a-zA-Z]+_") %>%
  stringr::str_remove("_") %>%
  stringr::str_replace("\\.", " ")

SDM_df <- data.frame(filepath = SDM_filepaths,
                     filename = basename(SDM_filepaths),
                     species = SDM_species)

SDM_obs_df <- merge(SDM_df, bowen_SDM_obs_focal_df, by = "species")

SDM_obs_df_bowen <- SDM_obs_df %>%
  filter(species %in% bowen_focal_list)

# Prepare SDM stack
SDM_stack <- list()
the_crs <- "+proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
bowen_shoreline <- terra::vect("RawData/shoreline_dem_smoothed2/shoreline_dem_smoothed2.shp") %>%
  terra::project(the_crs)
weights <- matrix(c(0, 0, 1, 1, 1, 0, 0,
                    0, 1, 1, 2, 1, 1, 0,
                    1, 1, 3, 3, 3, 1, 1,
                    1, 2, 3, 5, 3, 2, 1,
                    1, 1, 3, 3, 3, 1, 1,
                    0, 1, 1, 2, 1, 1, 0,
                    0, 0, 1, 1, 1, 0, 0
                    ), nrow=7)
for(i in 1:length(SDM_obs_df_bowen$filepath)) {
  SDM <- terra::rast(SDM_obs_df_bowen$filepath[i]) %>%
    terra::project(y = the_crs) %>%
    terra::focal(w = weights, 
                 fun = "mean",
                 na.policy = "only") %>%
    terra::mask(bowen_shoreline)
  SDM_stack[[i]] <- SDM
}
SDM_stack <- SDM_stack %>%
  terra::rast()

SDM_stack %>% sum(na.rm = T) %>% plot()

source("R/utils-sdm.R")
total_richness <- sdm_to_species_richness(SDM_stack = SDM_stack)
total_richness %>% plot()
```

```{r}
source("R/plots.R")

title <- "Bird Biodiversity Hotspots on Bowen Island"
subtitle <- "Relative biodiversity of Bird species derived from Species Distribution Models (SDMs) confirmed by citizen science observations submitted to eBird. Values towards 1.0 indicate higher relative biodiversity, while values towards 0.0 indicate lower relative biodiversity."
caption <- "Visualization created by Jay H. Matsushiba (jmatsush@sfu.ca) for the Palen Lab (November 2024)"

output_plot <- bowen_map(rel_biodiversity,
                         title,
                         subtitle,
                         caption)

# Save as PNG
ggplot2::ggsave(
  "Figures/2024_12_06_output.png", 
  output_plot, 
  device = ragg::agg_png, 
  width = 9, height = 12, units = "in", res = 300
)

```



