---
title: "Bowen Biodiversity SDMs"
author: "Jay Matsushiba"
date: "2024-12-11"
output: "html_document"
---

# Creating Bowen Biodiversity SDMs
This document shows the process for creating the Bowen Biodiversity SDMs.
- SDMs have been cropped to Bowen Island shoreline extent. 
- SDMs extrapolated to full Bowen Island extent where missing values, using weighted mean moving window algorithm (terra::focal()) 
- SDMs smoothed using weighted mean moving window algorithm

```{r setup}
# Internal packages developed / modified by Jay Matsushiba
library(sdmcsr)
library(rinat)
# CRAN packages
library(tidyverse)
library(terra)
library(sf)

# # Min SDM cell value somewhere on Bowen Island for including species into focal list.
include_threshold <- 0.5  
# # Min SDM cell value for a given cell for species to be considered present.
# present_threshold <- 0.7
```

```{r focal_list}
# Available SDMs
SDM_dir <- "RawData/2024_11_28_SDM_Bowen_Island/"
SDM_filepaths <- list.files(SDM_dir, recursive = T, full.names = T) 
SDM_filepaths <- SDM_filepaths[grepl("_NAs_", SDM_filepaths)]

# Create species list from available SDMs
species_list <- SDM_filepaths %>%
  basename() %>%
  stringr::str_extract("^\\S+\\.[a-zA-Z]+_") %>%
  stringr::str_remove("_") %>%
  stringr::str_replace("\\.", " ")

# Previous R chunk output
bowen_SDM_iNat <- read.csv("ProcessedData/2024_11_29_SDM_CS_all_species")

# Mammal presences from Pottinger Gaherty Environmental Consultants, Ltd.(January 2005) 
bowen_mammals <- readxl::read_xlsx("RawData/Appendix 2 - Expected Occurrence of Wildlife Species In The Cape Roger Curtis Area.xlsx", 
                                   sheet = "mammals") %>%
  filter(`Documented on Bowen` == "y" | `Documented on Bowen` == "?" | `Documented on Bowen` == "One or more spp" )

# Number of eBird observations by bird species on Bowen Island
## Results from Natasha Beauregard (Summer 2024 USRA)
bowen_birds <- read.csv("RawData/final_bird.csv") %>%
  select(c("scientific_name", "n_ebird"))

bowen_SDM_iNat_ebird <- merge(bowen_SDM_iNat, 
                              bowen_birds, 
                              by.x = "species", 
                              by.y = "scientific_name",
                              all.x = TRUE) %>%
  rename(n_obs_inat = inat_n_obs,
         n_obs_ebird = n_ebird) %>%
  select(
    species,
    sdm_max_value,
    taxon_group,
    n_obs_inat,
    n_obs_ebird
  )

bowen_SDM_obs_focal_df <- bowen_SDM_iNat_ebird %>%
  mutate(include = case_when(
    (n_obs_inat > 0 | n_obs_ebird > 0 ) & sdm_max_value > include_threshold ~ "y",
    species %in% bowen_mammals$`Scientific name` ~ "y"
  )
  )

# Create list of species names to include
bowen_focal_list <- bowen_SDM_obs_focal_df %>%
  filter(include == "y") %>%
  select(species) 
bowen_focal_list <- bowen_focal_list$species %>%
  unlist() %>%
  unname() 

SDM_df <- data.frame(filepath = SDM_filepaths,
                     filename = basename(SDM_filepaths),
                     species = species_list)
# Focal species
SDM_obs_df <- merge(SDM_df, bowen_SDM_obs_focal_df, by = "species")
# write.csv(SDM_obs_df, "ProcessedData/2024_12_10_SDM_CS_all_species.csv")

# Dataframe for focal species on Bowen Island
SDM_obs_df_bowen <- SDM_obs_df %>%
  filter(species %in% bowen_focal_list)
```

```{r sdm}
# Focal species
# SDM_obs_df <- read.csv("ProcessedData/2024_12_10_SDM_CS_all_species.csv")
SDM_obs_df_bowen <- SDM_obs_df %>%
  filter(species %in% bowen_focal_list)

# Prepare SDM stack
SDM_stack <- list()

# Defining CRS to make sure all SDMs have the same
the_crs <- "+proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"

# Bowen Shoreline polygon for masking the rasters 
bowen_shoreline <- terra::vect("RawData/shoreline_dem_smoothed2/shoreline_dem_smoothed2.shp") %>%
  terra::project(the_crs)
bowen_boundary <- terra::vect("RawData/bowen_boundary/Bowen_boundary.shp")

source("R/utils-sdm.R")
# Looping through SDMs to prepare as raster stack
for(i in 1:length(SDM_obs_df_bowen$filepath)) {
  SDM <- terra::rast(SDM_obs_df_bowen$filepath[i]) %>%
    raster_prep_bowen(bowen_boundary,
                      bowen_shoreline,
                      the_crs)
  SDM_stack[[i]] <- SDM
}
SDM_stack <- SDM_stack %>%
  terra::rast()

# Plot to check resulting raster stack
SDM_stack %>% sum(na.rm = T) %>% plot()

SDM_stack_paths <- SDM_obs_df_bowen$filepath %>%
  gsub("RawData/2024_11_28_SDM_Bowen_Island", "ProcessedData/2024_12_11_SDM_100m_Bowen_Island", .) %>%
  gsub("_NAs_pu_mask", "_BowenIsland_100m", .)

SDM_stack_directories <- SDM_stack_paths %>%
  dirname() %>%
  unique()

for(dir in 1:length(SDM_stack_directories)) {
  if(!dir.exists(SDM_stack_directories[dir])) {
    dir.create(SDM_stack_directories[dir],
               recursive = T)
  }
}

terra::writeRaster(SDM_stack, SDM_stack_paths, overwrite = T)
```

